repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [-C, .woped-hooks/.gitlint, --contrib=contrib-title-conventional-commits, --msg-filename]
  - repo: local
    hooks:
      - id: format-java-code
        name: format Java code with google-java-format
        entry: mvn spotless:apply
        language: system
        types: [java]
        stages: [pre-commit]
        pass_filenames: false
      - id: check-branch-name-post-checkout
        name: check branch name for compliance with GitHub Flow
        entry: "bash -lc 'python3 .woped-hooks/hooks/post-checkout.py \"$@\" || python .woped-hooks/hooks/post-checkout.py \"$@\" || py -3 .woped-hooks/hooks/post-checkout.py \"$@\"' ignore"
        language: system
        stages: [post-checkout]
        pass_filenames: false
        always_run: true